### PR TITLE
updated/fixed hauler directory

### LINKED ISSUE #249: [BUG] Hauler cannot load copy images to registry from RHEL8 system when $HOME has noexec flag set
**Environmental Info:**

- Linux <hostname> 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Hauler Version:**

- GitVersion: 1.0.3
- GitCommit: 7fc24f6
- GitTreeState: clean

**Describe the Bug:**

- When attempting to run `hauler store copy <registry>` on a RHEL8 STIG'd system, hauler throws an error `ERR fork/exec /home/<user>/.hauler/cosign: operation not permitted"`

**Steps to Reproduce:**

- Copy Hauler to any authorized path (without noexec flag set) (e.g., /usr/local/bin)
- Load images into local airgapped store: `hauler store load <archive>`
- Run `hauler store copy registry://<registry>`
- Observe the error above

**Expected Behavior:**

- Command should run to completion.

**Actual Behavior:**

- `cosign` attempts to run from inside `${HOME}/.hauler/cosign`. This is unauthorized behavior according to DISA and blocked.

**Additional Context:**

- Need to be able to specify another path or, preferably, an external cosign binary that is pre-positioned

### LINKED ISSUE #360: [BUG] error logging into registry: fork/exec /root/.hauler/cosign: operation not permitted
**Environmental Info:**

Linux rke2-server 5.15.0-209.161.7.2.el8uek.x86_64 #2 SMP Tue Aug 20 10:44:07 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux
-

**Hauler Version:**

image

-

**Describe the Bug:**

`hauler login` fails, where `cosign login`/`ctr login`/`crictl login` succeed.  
-

**Steps to Reproduce:**

1. Create VM with Oracle Linux 8, with a single network interface, connected to the internet
2. `curl -sfL https://get.hauler.dev | bash`
3. `hauler login regsitry1.dso.mil -u <my username> -p <my password>`

-

**Expected Behavior:**

Receive a `login succeeded` messaeg.
-

**Actual Behavior:**

Here is a screenshot demonstrating `hauler` failing to login (left terminal) while `ctr` is able to login and pull an image (right terminal).
image

Here is an example of using `cosign`, which was installed along with `hauler`, to login to the target repository.
image

-

**Additional Context:**

As of ~3 weeks ago I had another VM and was able to install `hauler` via the command listed above, login to the registry, and add images to my image store. That is to say-- this is new behavior.
-

### PR DESCRIPTION
**Pull request by zackbradys**
**Please check below, if the PR fulfills these requirements:**
- [X] Commit(s) and code follow the repositories guidelines.
- [X] Test(s) have been added or updated to support these change(s).
- [X] Doc(s) have been added or updated to support these change(s).

**Associated Links:**

- https://github.com/hauler-dev/hauler/issues/249

**Types of Changes:**

- Feature

**Proposed Changes:**

- Added environment variable to configure the location of the `hauler` directory... `HAULER_DIR`
  - this directory is used for storing all config files, `install.sh` artifacts, and binaries
- Updated the `install.sh` script to use the same environment variable/argument as `HAULER_DIR` instead of the previously hard coded `$HOME/.hauler`
- Added environment variable to configure the location of the `hauler` temp directory... `HAULER_TEMP_DIR`
  - this directory is used for temporarily storing artifacts when using various commands
- Added small comments to `hauler/hauler help` to state available environment variables

**Verification/Testing of Changes:**

- `git clone https://github.com/zackbradys/hauler.git && cd hauler && make build`

#### Changes to CLI Comments...
```bash
zackbradys@Zacks-MacBook-Pro hauler % ./dist/hauler_darwin_arm64/hauler 
Airgap Swiss Army Knife

Usage:
  hauler [flags]
  hauler [command]

Examples:
  View the Docs: https://docs.hauler.dev
  Environment Variables: HAULER_DIR | HAULER_TEMP_DIR

Available Commands:
  completion  Generate auto-completion scripts for various shells
  help        Help about any command
  login       Login to a registry
  store       Interact with the content store
  version     Print the current version

Flags:
  -h, --help               help for hauler
  -l, --log-level string    (default "info")

Use "hauler [command] --help" for more information about a command.
```

#### New `HAULER_DIR` Environment Variable...
```bash
zackbradys@Zacks-MacBook-Pro hauler % ./dist/hauler_darwin_arm64/hauler store info
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@Zacks-MacBook-Pro hauler % ls /Users/zackbradys/.hauler
cosign
zackbradys@Zacks-MacBook-Pro hauler % rm -rf /Users/zackbradys/.hauler
zackbradys@Zacks-MacBook-Pro hauler % ls /Users/zackbradys/.hauler    
ls: /Users/zackbradys/.hauler: No such file or directory
```

```bash
zackbradys@Zacks-MacBook-Pro hauler % export HAULER_DIR=/Users/zackbradys/Downloads/haulertesting 
zackbradys@Zacks-MacBook-Pro hauler % ./dist/hauler_darwin_arm64/hauler store info
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@Zacks-MacBook-Pro hauler % ls /Users/zackbradys/.hauler 
ls: /Users/zackbradys/.hauler: No such file or directory
zackbradys@Zacks-MacBook-Pro hauler % ls /Users/zackbradys/Downloads/haulertesting 
cosign
```

#### New `HAULER_TEMP_DIR` Environment Variable...
```bash
zackbradys@Zacks-MacBook-Pro hauler % ./dist/hauler_darwin_arm64/hauler store load testdata/haul.tar.zst
2024-11-02 15:03:00 INF loading content from [testdata/haul.tar.zst] to [store]

zackbradys@Zacks-MacBook-Pro ~ % fswatch -0 /var/folders/5f/lyy8pc6s62dbckp8sy31ft5r0000gn/T/ | grep -z "hauler" 
/private/var/folders/5f/lyy8pc6s62dbckp8sy31ft5r0000gn/T/hauler1872136313/oci-layout .... everything else
```

```bash
zackbradys@Zacks-MacBook-Pro hauler % export HAULER_TEMP_DIR=/Users/zackbradys/Downloads/haulertesting/temp 
zackbradys@Zacks-MacBook-Pro hauler % ./dist/hauler_darwin_arm64/hauler store load testdata/haul.tar.zst   
2024-11-02 15:06:40 INF loading content from [testdata/haul.tar.zst] to [store]

zackbradys@Zacks-MacBook-Pro ~ % fswatch -0 /var/folders/5f/lyy8pc6s62dbckp8sy31ft5r0000gn/T/ | grep -z "hauler"

zackbradys@Zacks-MacBook-Pro haulertesting % fswatch -0 temp | grep -z "hauler"
/Users/zackbradys/Downloads/haulertesting/temp/hauler236565745/oci-layout .... everything else
```

#### New `HAULER_DIR` to `install.sh`...
```bash
zackbradys@Zacks-MacBook-Pro Downloads % curl -sfL https://raw.githubusercontent.com/zackbradys/hauler/refs/heads/fixed-hauler-directory/install.sh | sudo HAULER_DIR=/opt/hauler bash

[INFO] Hauler: Starting Preflight Checks...

[INFO] Hauler: Starting Installation...
- Version: v1.1.0
- Platform: darwin
- Architecture: arm64
- Install Directory: /usr/local/bin
- Hauler Directory: /opt/hauler

[INFO] Hauler: Starting Download...

[INFO] Hauler: Starting Checksum Verification...
- Expected Checksum: 8b03f8b7f49dcfe5eaa1e143bffbd2c0625d792dec0e55dce79b1c48e6da7a8c
- Determined Checksum: 8b03f8b7f49dcfe5eaa1e143bffbd2c0625d792dec0e55dce79b1c48e6da7a8c
- Successfully Verified Checksum: hauler_1.1.0_darwin_arm64.tar.gz

[INFO] Hauler: Successfully Installed Hauler at /usr/local/bin/hauler

[INFO] Hauler: Hauler v1.1.0 is now available for use!
- Documentation: https://hauler.dev
```

### CODE REVIEW

File: cmd/hauler/cli/store/load.go [hunk 1]
```diff
@@ -30,17 +30,21 @@ func LoadCmd(ctx context.Context, o *flags.LoadOpts, archiveRefs ...string) erro
 
 // unarchiveLayoutTo accepts an archived oci layout and extracts the contents to an existing oci layout, preserving the index
 func unarchiveLayoutTo(ctx context.Context, archivePath string, dest string, tempOverride string) error {
-	tmpdir, err := os.MkdirTemp(tempOverride, "hauler")
+	if tempOverride == "" {
+		tempOverride = os.Getenv("HAULER_TEMP_DIR")
```
Comment (dweomer) [inline cmd/hauler/cli/store/load.go]:
```suggestion
		tempOverride = os.Getenv("HAULER_TEMP")
```

**Comment by amartin120** [comment]
Outside of any variable name suggestions from @dweomer, I'm happy with this PR.  Thanks for tackling @zackbradys. 

@hauler-dev/maintainers We should make sure that this is documented well.  Maybe even include examples in the GitHub release notes whenever it's  released.

File: pkg/cosign/cosign.go [hunk 2]
```diff
@@ -256,7 +256,10 @@ func getCosignPath() (string, error) {
 	homeDir := currentUser.HomeDir
 
 	// Construct the path to the .hauler directory
-	haulerDir := filepath.Join(homeDir, ".hauler")
+	haulerDir := os.Getenv("HAULER_DIR")
```
Comment (dweomer) [inline pkg/cosign/cosign.go]:
```suggestion
	haulerDir := os.Getenv("HAULER_HOME")
```

File: cmd/hauler/cli/store/load.go (hunk 1 above)
Comment (zackbradys) [reply cmd/hauler/cli/store/load.go]: Hey @dweomer... would we also want to update the flag of `--tempdir/-t`? I was trying to match it with this ENV variable, but okay with this update...

File: pkg/cosign/cosign.go (hunk 2 above)
Comment (zackbradys) [reply pkg/cosign/cosign.go]: Okay with this one... will update it with a PR once you see the other comment... @dweomer

**Comment by zackbradys** [comment]
> Outside of any variable name suggestions from @dweomer, I'm happy with this PR. Thanks for tackling @zackbradys.
> 
> @hauler-dev/maintainers We should make sure that this is documented well. Maybe even include examples in the GitHub release notes whenever it's released.

I agree... I'll start work on a first draft of docs... @amartin120 @CamrynCarter

**Review by dweomer — DISMISSED** [review]
This looks fine, but we should probably bite the bullet and provide flag parity with the new envvars, aka `--hauler-home` and `--hauler-temp` (or `--home` and `--temp`) flags with the envvars overriding the default values for the flags.

**Comment by zackbradys** [comment]
```bash
zackbradys@MacBookPro hauler % ./dist/hauler_darwin_arm64_v8.0/hauler store info
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@MacBookPro hauler % ./check.sh                                       

checking ~/.hauler...
cosign

checking ~/.haulersss...
ls: /Users/zackbradys/.haulersss: No such file or directory

checking ~/.haulersssss...
ls: /Users/zackbradys/.haulersssss: No such file or directory

removing directories...

zackbradys@MacBookPro hauler % ./dist/hauler_darwin_arm64_v8.0/hauler store info --haulerdir ~/.haulersss
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@MacBookPro hauler % ./check.sh                                                                

checking ~/.hauler...
ls: /Users/zackbradys/.hauler: No such file or directory

checking ~/.haulersss...
cosign

checking ~/.haulersssss...
ls: /Users/zackbradys/.haulersssss: No such file or directory

removing directories...

zackbradys@MacBookPro hauler % export HAULER_DIR=~/.haulersssss
zackbradys@MacBookPro hauler % ./dist/hauler_darwin_arm64_v8.0/hauler store info --haulerdir ~/.haulersss
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@MacBookPro hauler % ./check.sh                                                                

checking ~/.hauler...
ls: /Users/zackbradys/.hauler: No such file or directory

checking ~/.haulersss...
cosign

checking ~/.haulersssss...
ls: /Users/zackbradys/.haulersssss: No such file or directory

removing directories...

zackbradys@MacBookPro hauler % ./dist/hauler_darwin_arm64_v8.0/hauler store info                         
+-----------+------+----------+----------+------+
| REFERENCE | TYPE | PLATFORM | # LAYERS | SIZE |
+-----------+------+----------+----------+------+
+-----------+------+----------+----------+------+
|                                TOTAL   | 0 B  |
+-----------+------+----------+----------+------+
zackbradys@MacBookPro hauler % ./check.sh                                       

checking ~/.hauler...
ls: /Users/zackbradys/.hauler: No such file or directory

checking ~/.haulersss...
ls: /Users/zackbradys/.haulersss: No such file or directory

checking ~/.haulersssss...
cosign

removing directories...

```

File: install.sh [hunk 3]
```diff
@@ -124,29 +128,33 @@ case $ARCH in
...
-verbose "- Architecture: $ARCH"
+verbose "- Platform: ${PLATFORM}"
+verbose "- Architecture: ${ARCH}"
 verbose "- Install Directory: ${HAULER_INSTALL_DIR}"
+verbose "- Hauler Directory: ${HAULER_DIR}"
 
-# check working directory and/or create it
-if [ ! -d "$HOME/.hauler" ]; then
-    mkdir -p "$HOME/.hauler" || fatal "Failed to Create Directory: $HOME/.hauler"
+# ensure hauler directory exists and/or create it
```
Comment (dweomer) [inline install.sh:148]: this chunk of script predates these changes but i wanted to drop a comment, at least as a reminder to myself, asking why we care about this location in the installation script?

File: pkg/consts/consts.go [hunk 4]
```diff
@@ -61,13 +61,32 @@ const (
...
 	// other constraints
-	CarbideRegistry   = "rgcrprod.azurecr.us"
-	APIVersion        = "v1alpha1"
-	DefaultNamespace  = "hauler"
-	DefaultTag        = "latest"
-	DefaultStoreName  = "store"
-	DefaultRetries    = 3
-	RetriesInterval   = 5
-	OCIImageIndexFile = "index.json"
+	CarbideRegistry          = "rgcrprod.azurecr.us"
```
Comment (dweomer) [inline pkg/consts/consts.go:76]: `CarbideRegistry` should really be a `var` so that one has the option to override it via `go build` flags, i.e. `-X hauler.dev/go/hauler/pkg/consts.CarbideRegistry=example.com`

File: pkg/consts/consts.go [hunk 5]
```diff
@@ -61,13 +61,32 @@ const (
...
 
+	// environment variables
+	HaulerDir     = "HAULER_DIR"
+	HaulerTempDir = "HAULER_TEMP_DIR"
+
+	// container files and directories
+	OCIImageIndexFile    = "index.json"
+	OCIImageManifestFile = "manifest.json"
+	OCIImageConfigFile   = "config.json"
+	OCIImageLayoutFile   = "oci-layout"
```
Comment (dweomer) [inline pkg/consts/consts.go:72]: - https://github.com/opencontainers/image-spec/blob/v1.1.0/specs-go/v1/layout.go#L19

File: pkg/consts/consts.go [hunk 6]
```diff
@@ -61,13 +61,32 @@ const (
 	ContentGroup    = "content.hauler.cattle.io"
 	CollectionGroup = "collection.hauler.cattle.io"
 
+	// environment variables
+	HaulerDir     = "HAULER_DIR"
+	HaulerTempDir = "HAULER_TEMP_DIR"
+
+	// container files and directories
+	OCIImageIndexFile    = "index.json"
```
Comment (dweomer) [inline pkg/consts/consts.go:69]: - https://github.com/opencontainers/image-spec/blob/v1.1.0/specs-go/v1/layout.go#L23

File: pkg/consts/consts.go [hunk 7]
```diff
@@ -61,13 +61,32 @@ const (
...
+	OCIImageManifestFile = "manifest.json"
+	OCIImageConfigFile   = "config.json"
+	OCIImageLayoutFile   = "oci-layout"
+	OCIImageBlobsDir     = "blobs"
```
Comment (dweomer) [inline pkg/consts/consts.go:73]: - https://github.com/opencontainers/image-spec/blob/v1.1.0/specs-go/v1/layout.go#L25

File: pkg/consts/consts.go [hunk 8]
```diff
@@ -61,13 +61,32 @@ const (
...
 	CollectionGroup = "collection.hauler.cattle.io"
 
+	// environment variables
+	HaulerDir     = "HAULER_DIR"
+	HaulerTempDir = "HAULER_TEMP_DIR"
+
+	// container files and directories
+	OCIImageIndexFile    = "index.json"
+	OCIImageManifestFile = "manifest.json"
+	OCIImageConfigFile   = "config.json"
```
Comment (dweomer) [inline pkg/consts/consts.go:71]: these two are misnamed as they aren't specified in either the image-spec nor runtime-spec. i dunno what the prefix should be but the use of OCI is misleading.

File: pkg/cosign/cosign.go [hunk 9]
```diff
@@ -243,35 +250,38 @@ func EnsureBinaryExists(ctx context.Context, bin embed.FS) error {
...
 	}
 
-	// Get the user's home directory
-	homeDir := currentUser.HomeDir
+	if haulerDir == "" {
+		// Get the current user's information
+		currentUser, err := user.Current()
+		if err != nil {
+			return "", fmt.Errorf("error retrieving user information: %v", err)
+		}
```
Comment (dweomer) [inline pkg/cosign/cosign.go:263]: we should log this at `WARN` and move on to try https://pkg.go.dev/os#UserHomeDir

**Review by dweomer — APPROVED** [review]
okay, so, left a bunch of nits that we don't necessarily need to address right now.

File: pkg/consts/consts.go (hunk 4 above)
Comment (zackbradys) [reply pkg/consts/consts.go:76]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/365

File: pkg/consts/consts.go (hunk 7 above)
Comment (zackbradys) [reply pkg/consts/consts.go:73]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/363

File: pkg/consts/consts.go (hunk 5 above)
Comment (zackbradys) [reply pkg/consts/consts.go:72]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/363

File: pkg/consts/consts.go (hunk 6 above)
Comment (zackbradys) [reply pkg/consts/consts.go:69]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/363

File: pkg/consts/consts.go (hunk 8 above)
Comment (zackbradys) [reply pkg/consts/consts.go:71]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/366

File: pkg/cosign/cosign.go (hunk 9 above)
Comment (zackbradys) [reply pkg/cosign/cosign.go:263]: Conversation moved to Issue https://github.com/hauler-dev/hauler/issues/367

File: install.sh (hunk 3 above)
Comment (zackbradys) [reply install.sh:148]: outputs the artifacts from the `install.sh`. no reason it is in `$HOME/.hauler` except for the fact that is what we have been using for the known location of `hauler` bits...

Comment (zackbradys) [reply install.sh:148]: Conversation continued in Discussion https://github.com/hauler-dev/hauler/discussions/364
