### PR TITLE
continue on error when adding images to store

### LINKED ISSUE #315: [BUG] Hauler fails to pull Rancher v2.9.x linux/amd64 due to mirrored-prometheus-windows-exporter
**Environmental Info:**
- Linux hauler 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Hauler Version:**
```
root@hauler:~# hauler version
 __    __       ___       __    __   __       _______ .______
|  |  |  |     /   \     |  |  |  | |  |     |   ____||   _  \
|  |__|  |    /  ^  \    |  |  |  | |  |     |  |__   |  |_)  |
|   __   |   /  /_\  \   |  |  |  | |  |     |   __|  |      /
|  |  |  |  /  _____  \  |  `--'  | |  `----.|  |____ |  |\  \----.
|__|  |__| /__/     \__\  \______/  |_______||_______|| _| `._____|
hauler: Airgap Swiss Army Knife

GitVersion:    1.0.7
GitCommit:     c592551
GitTreeState:  clean
BuildDate:     2024-08-13T19:23:45Z
GoVersion:     go1.21.12
Compiler:      gc
Platform:      linux/amd64
```

**Describe the Bug:**

- When using the following command from our documentation to pull down Rancher v2.9.x with the platform flag, Hauler fails to pull down mirrored-prometheus-windows-exporter as it's a Windows only image, and doesn't exist for linux/amd64. However, this image is still in the manifests, and Hauler will NOT continue on with the rest of the manifest ( ref: #296 )

**Steps to Reproduce:**
```
hauler store sync --store image-store --products rancher=v2.9.1 --key carbide-key.pub --platform linux/amd64
```

**Expected Behavior:**
- Hauler should NOT try to pull down this image on the linux/amd64 platform

**Actual Behavior:**
- Hauler attempts to pull down this image, and it fails and will NOT pull down the rest of the images.

### PR DESCRIPTION
**Pull request by amartin120**
**Please check below, if the PR fulfills these requirements:**
- [x] Commit(s) and code follow the repositories guidelines.
- [ ] Test(s) have been added or updated to support these change(s).
- [ ] Doc(s) have been added or updated to support these change(s).

**Associated Links:**

- https://github.com/hauler-dev/hauler/issues/315

**Types of Changes:**

- Feature

**Proposed Changes:**

- log errors from `cosign save` as warnings and continue operations.

**Verification/Testing of Changes:**

- Here's an example of hitting a failure and hauler keeps on truckin'.
image

**Additional Context:**

-

### CODE REVIEW

File: cmd/hauler/cli/store/add.go [hunk 1]
```diff
@@ -76,12 +76,14 @@ func storeImage(ctx context.Context, s *store.Layout, i v1alpha1.Image, platform
 
 	r, err := name.ParseReference(i.Name)
 	if err != nil {
-		return err
+		l.Warnf("unable to add 'image' [%s] to store.  skipping...", r.Name())
```
Comment (dweomer) [inline cmd/hauler/cli/store/add.go]:
```suggestion
		l.Warnf("unable to parse 'image' [%s], skipping...", r.Name())
```

File: cmd/hauler/cli/store/add.go [hunk 2]
```diff
@@ -76,12 +76,14 @@ func storeImage(ctx context.Context, s *store.Layout, i v1alpha1.Image, platform
...
+		return nil
 	}
 
 	err = cosign.SaveImage(ctx, s, r.Name(), platform)
 	if err != nil {
-		return err
+		l.Warnf("unable to add 'image' [%s] to store.  skipping...", r.Name())
```
Comment (dweomer) [inline cmd/hauler/cli/store/add.go:85]: this feels like a contract-breaking change until we have more time to analyze. we should be parsing the error and emitting a warning if a platform has ben specified and we cannot find a reference to an image for such in the manifest (or its a single-arch ref and the specified platform is mismatched with the image platform)

**Review by dweomer — APPROVED** [review]
